// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.3
// source: middle.proto

package apitest

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MiddleClient is the client API for Middle service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MiddleClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type middleClient struct {
	cc grpc.ClientConnInterface
}

func NewMiddleClient(cc grpc.ClientConnInterface) MiddleClient {
	return &middleClient{cc}
}

func (c *middleClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/test.Middle/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MiddleServer is the server API for Middle service.
// All implementations must embed UnimplementedMiddleServer
// for forward compatibility
type MiddleServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloResponse, error)
	mustEmbedUnimplementedMiddleServer()
}

// UnimplementedMiddleServer must be embedded to have forward compatible implementations.
type UnimplementedMiddleServer struct {
}

func (UnimplementedMiddleServer) SayHello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedMiddleServer) mustEmbedUnimplementedMiddleServer() {}

// UnsafeMiddleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MiddleServer will
// result in compilation errors.
type UnsafeMiddleServer interface {
	mustEmbedUnimplementedMiddleServer()
}

func RegisterMiddleServer(s grpc.ServiceRegistrar, srv MiddleServer) {
	s.RegisterService(&Middle_ServiceDesc, srv)
}

func _Middle_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiddleServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/test.Middle/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiddleServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Middle_ServiceDesc is the grpc.ServiceDesc for Middle service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Middle_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "test.Middle",
	HandlerType: (*MiddleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Middle_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "middle.proto",
}
