// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.22.3
// source: rest.proto

package apitest

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RestServiceClient is the client API for RestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RestServiceClient interface {
	Echo(ctx context.Context, in *EchoMessageRequest, opts ...grpc.CallOption) (*EchoMessageResponse, error)
}

type restServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRestServiceClient(cc grpc.ClientConnInterface) RestServiceClient {
	return &restServiceClient{cc}
}

func (c *restServiceClient) Echo(ctx context.Context, in *EchoMessageRequest, opts ...grpc.CallOption) (*EchoMessageResponse, error) {
	out := new(EchoMessageResponse)
	err := c.cc.Invoke(ctx, "/RestService/Echo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RestServiceServer is the server API for RestService service.
// All implementations must embed UnimplementedRestServiceServer
// for forward compatibility
type RestServiceServer interface {
	Echo(context.Context, *EchoMessageRequest) (*EchoMessageResponse, error)
	mustEmbedUnimplementedRestServiceServer()
}

// UnimplementedRestServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRestServiceServer struct {
}

func (UnimplementedRestServiceServer) Echo(context.Context, *EchoMessageRequest) (*EchoMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Echo not implemented")
}
func (UnimplementedRestServiceServer) mustEmbedUnimplementedRestServiceServer() {}

// UnsafeRestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RestServiceServer will
// result in compilation errors.
type UnsafeRestServiceServer interface {
	mustEmbedUnimplementedRestServiceServer()
}

func RegisterRestServiceServer(s grpc.ServiceRegistrar, srv RestServiceServer) {
	s.RegisterService(&RestService_ServiceDesc, srv)
}

func _RestService_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestServiceServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RestService/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestServiceServer).Echo(ctx, req.(*EchoMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RestService_ServiceDesc is the grpc.ServiceDesc for RestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "RestService",
	HandlerType: (*RestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _RestService_Echo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rest.proto",
}
