// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.22.3
// source: types_def.proto

package apitest

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WithInt64RequestResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int64 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *WithInt64RequestResponse) Reset() {
	*x = WithInt64RequestResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_def_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithInt64RequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithInt64RequestResponse) ProtoMessage() {}

func (x *WithInt64RequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_def_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithInt64RequestResponse.ProtoReflect.Descriptor instead.
func (*WithInt64RequestResponse) Descriptor() ([]byte, []int) {
	return file_types_def_proto_rawDescGZIP(), []int{0}
}

func (x *WithInt64RequestResponse) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type WithOneofRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to OneOfValue:
	//
	//	*WithOneofRequest_Number
	//	*WithOneofRequest_Text
	OneOfValue isWithOneofRequest_OneOfValue `protobuf_oneof:"one_of_value"`
	Type       string                        `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *WithOneofRequest) Reset() {
	*x = WithOneofRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_def_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithOneofRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithOneofRequest) ProtoMessage() {}

func (x *WithOneofRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_def_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithOneofRequest.ProtoReflect.Descriptor instead.
func (*WithOneofRequest) Descriptor() ([]byte, []int) {
	return file_types_def_proto_rawDescGZIP(), []int{1}
}

func (m *WithOneofRequest) GetOneOfValue() isWithOneofRequest_OneOfValue {
	if m != nil {
		return m.OneOfValue
	}
	return nil
}

func (x *WithOneofRequest) GetNumber() int64 {
	if x, ok := x.GetOneOfValue().(*WithOneofRequest_Number); ok {
		return x.Number
	}
	return 0
}

func (x *WithOneofRequest) GetText() string {
	if x, ok := x.GetOneOfValue().(*WithOneofRequest_Text); ok {
		return x.Text
	}
	return ""
}

func (x *WithOneofRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type isWithOneofRequest_OneOfValue interface {
	isWithOneofRequest_OneOfValue()
}

type WithOneofRequest_Number struct {
	Number int64 `protobuf:"varint,1,opt,name=number,proto3,oneof"`
}

type WithOneofRequest_Text struct {
	Text string `protobuf:"bytes,2,opt,name=text,proto3,oneof"`
}

func (*WithOneofRequest_Number) isWithOneofRequest_OneOfValue() {}

func (*WithOneofRequest_Text) isWithOneofRequest_OneOfValue() {}

type WithOneofResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to OneOfValue:
	//
	//	*WithOneofResponse_Number
	//	*WithOneofResponse_Text
	OneOfValue isWithOneofResponse_OneOfValue `protobuf_oneof:"one_of_value"`
}

func (x *WithOneofResponse) Reset() {
	*x = WithOneofResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_def_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithOneofResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithOneofResponse) ProtoMessage() {}

func (x *WithOneofResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_def_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithOneofResponse.ProtoReflect.Descriptor instead.
func (*WithOneofResponse) Descriptor() ([]byte, []int) {
	return file_types_def_proto_rawDescGZIP(), []int{2}
}

func (m *WithOneofResponse) GetOneOfValue() isWithOneofResponse_OneOfValue {
	if m != nil {
		return m.OneOfValue
	}
	return nil
}

func (x *WithOneofResponse) GetNumber() int64 {
	if x, ok := x.GetOneOfValue().(*WithOneofResponse_Number); ok {
		return x.Number
	}
	return 0
}

func (x *WithOneofResponse) GetText() string {
	if x, ok := x.GetOneOfValue().(*WithOneofResponse_Text); ok {
		return x.Text
	}
	return ""
}

type isWithOneofResponse_OneOfValue interface {
	isWithOneofResponse_OneOfValue()
}

type WithOneofResponse_Number struct {
	Number int64 `protobuf:"varint,1,opt,name=number,proto3,oneof"`
}

type WithOneofResponse_Text struct {
	Text string `protobuf:"bytes,2,opt,name=text,proto3,oneof"`
}

func (*WithOneofResponse_Number) isWithOneofResponse_OneOfValue() {}

func (*WithOneofResponse_Text) isWithOneofResponse_OneOfValue() {}

type WithPrimitiveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Primitive *PrimitiveType `protobuf:"bytes,1,opt,name=primitive,proto3" json:"primitive,omitempty"`
	Type      string         `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *WithPrimitiveRequest) Reset() {
	*x = WithPrimitiveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_def_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithPrimitiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithPrimitiveRequest) ProtoMessage() {}

func (x *WithPrimitiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_def_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithPrimitiveRequest.ProtoReflect.Descriptor instead.
func (*WithPrimitiveRequest) Descriptor() ([]byte, []int) {
	return file_types_def_proto_rawDescGZIP(), []int{3}
}

func (x *WithPrimitiveRequest) GetPrimitive() *PrimitiveType {
	if x != nil {
		return x.Primitive
	}
	return nil
}

func (x *WithPrimitiveRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type WithPrimitiveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Primitive *PrimitiveType `protobuf:"bytes,1,opt,name=primitive,proto3" json:"primitive,omitempty"`
}

func (x *WithPrimitiveResponse) Reset() {
	*x = WithPrimitiveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_def_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithPrimitiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithPrimitiveResponse) ProtoMessage() {}

func (x *WithPrimitiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_def_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithPrimitiveResponse.ProtoReflect.Descriptor instead.
func (*WithPrimitiveResponse) Descriptor() ([]byte, []int) {
	return file_types_def_proto_rawDescGZIP(), []int{4}
}

func (x *WithPrimitiveResponse) GetPrimitive() *PrimitiveType {
	if x != nil {
		return x.Primitive
	}
	return nil
}

type WithOptionalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OptionValue *int64 `protobuf:"varint,1,opt,name=option_value,json=optionValue,proto3,oneof" json:"option_value,omitempty"`
	Type        string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *WithOptionalRequest) Reset() {
	*x = WithOptionalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_def_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithOptionalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithOptionalRequest) ProtoMessage() {}

func (x *WithOptionalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_def_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithOptionalRequest.ProtoReflect.Descriptor instead.
func (*WithOptionalRequest) Descriptor() ([]byte, []int) {
	return file_types_def_proto_rawDescGZIP(), []int{5}
}

func (x *WithOptionalRequest) GetOptionValue() int64 {
	if x != nil && x.OptionValue != nil {
		return *x.OptionValue
	}
	return 0
}

func (x *WithOptionalRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type WithOptionalResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OptionValue *int64 `protobuf:"varint,1,opt,name=option_value,json=optionValue,proto3,oneof" json:"option_value,omitempty"`
}

func (x *WithOptionalResponse) Reset() {
	*x = WithOptionalResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_def_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithOptionalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithOptionalResponse) ProtoMessage() {}

func (x *WithOptionalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_def_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithOptionalResponse.ProtoReflect.Descriptor instead.
func (*WithOptionalResponse) Descriptor() ([]byte, []int) {
	return file_types_def_proto_rawDescGZIP(), []int{6}
}

func (x *WithOptionalResponse) GetOptionValue() int64 {
	if x != nil && x.OptionValue != nil {
		return *x.OptionValue
	}
	return 0
}

type WithRepeatedInt64Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IntArray []int64 `protobuf:"varint,1,rep,packed,name=int_array,json=intArray,proto3" json:"int_array,omitempty"`
	Type     string  `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *WithRepeatedInt64Request) Reset() {
	*x = WithRepeatedInt64Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_def_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithRepeatedInt64Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithRepeatedInt64Request) ProtoMessage() {}

func (x *WithRepeatedInt64Request) ProtoReflect() protoreflect.Message {
	mi := &file_types_def_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithRepeatedInt64Request.ProtoReflect.Descriptor instead.
func (*WithRepeatedInt64Request) Descriptor() ([]byte, []int) {
	return file_types_def_proto_rawDescGZIP(), []int{7}
}

func (x *WithRepeatedInt64Request) GetIntArray() []int64 {
	if x != nil {
		return x.IntArray
	}
	return nil
}

func (x *WithRepeatedInt64Request) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type WithRepeatedInt64Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IntArray []int64 `protobuf:"varint,1,rep,packed,name=int_array,json=intArray,proto3" json:"int_array,omitempty"`
}

func (x *WithRepeatedInt64Response) Reset() {
	*x = WithRepeatedInt64Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_def_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithRepeatedInt64Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithRepeatedInt64Response) ProtoMessage() {}

func (x *WithRepeatedInt64Response) ProtoReflect() protoreflect.Message {
	mi := &file_types_def_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithRepeatedInt64Response.ProtoReflect.Descriptor instead.
func (*WithRepeatedInt64Response) Descriptor() ([]byte, []int) {
	return file_types_def_proto_rawDescGZIP(), []int{8}
}

func (x *WithRepeatedInt64Response) GetIntArray() []int64 {
	if x != nil {
		return x.IntArray
	}
	return nil
}

type WithRepeatedStringIntRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StringIntArray []*StringIntegerValue `protobuf:"bytes,1,rep,name=string_int_array,json=stringIntArray,proto3" json:"string_int_array,omitempty"`
	Type           string                `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *WithRepeatedStringIntRequest) Reset() {
	*x = WithRepeatedStringIntRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_def_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithRepeatedStringIntRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithRepeatedStringIntRequest) ProtoMessage() {}

func (x *WithRepeatedStringIntRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_def_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithRepeatedStringIntRequest.ProtoReflect.Descriptor instead.
func (*WithRepeatedStringIntRequest) Descriptor() ([]byte, []int) {
	return file_types_def_proto_rawDescGZIP(), []int{9}
}

func (x *WithRepeatedStringIntRequest) GetStringIntArray() []*StringIntegerValue {
	if x != nil {
		return x.StringIntArray
	}
	return nil
}

func (x *WithRepeatedStringIntRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type WithRepeatedStringIntResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StringIntArray []*StringIntegerValue `protobuf:"bytes,1,rep,name=string_int_array,json=stringIntArray,proto3" json:"string_int_array,omitempty"`
}

func (x *WithRepeatedStringIntResponse) Reset() {
	*x = WithRepeatedStringIntResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_def_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithRepeatedStringIntResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithRepeatedStringIntResponse) ProtoMessage() {}

func (x *WithRepeatedStringIntResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_def_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithRepeatedStringIntResponse.ProtoReflect.Descriptor instead.
func (*WithRepeatedStringIntResponse) Descriptor() ([]byte, []int) {
	return file_types_def_proto_rawDescGZIP(), []int{10}
}

func (x *WithRepeatedStringIntResponse) GetStringIntArray() []*StringIntegerValue {
	if x != nil {
		return x.StringIntArray
	}
	return nil
}

type WithMapRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MapValue map[string]int64 `protobuf:"bytes,1,rep,name=map_value,json=mapValue,proto3" json:"map_value,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Type     string           `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *WithMapRequest) Reset() {
	*x = WithMapRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_def_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithMapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithMapRequest) ProtoMessage() {}

func (x *WithMapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_def_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithMapRequest.ProtoReflect.Descriptor instead.
func (*WithMapRequest) Descriptor() ([]byte, []int) {
	return file_types_def_proto_rawDescGZIP(), []int{11}
}

func (x *WithMapRequest) GetMapValue() map[string]int64 {
	if x != nil {
		return x.MapValue
	}
	return nil
}

func (x *WithMapRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type WithMapResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MapValue map[string]int64 `protobuf:"bytes,1,rep,name=map_value,json=mapValue,proto3" json:"map_value,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *WithMapResponse) Reset() {
	*x = WithMapResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_def_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithMapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithMapResponse) ProtoMessage() {}

func (x *WithMapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_types_def_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithMapResponse.ProtoReflect.Descriptor instead.
func (*WithMapResponse) Descriptor() ([]byte, []int) {
	return file_types_def_proto_rawDescGZIP(), []int{12}
}

func (x *WithMapResponse) GetMapValue() map[string]int64 {
	if x != nil {
		return x.MapValue
	}
	return nil
}

type PrimitiveType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value *PrimitiveType_Value `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *PrimitiveType) Reset() {
	*x = PrimitiveType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_def_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrimitiveType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrimitiveType) ProtoMessage() {}

func (x *PrimitiveType) ProtoReflect() protoreflect.Message {
	mi := &file_types_def_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrimitiveType.ProtoReflect.Descriptor instead.
func (*PrimitiveType) Descriptor() ([]byte, []int) {
	return file_types_def_proto_rawDescGZIP(), []int{13}
}

func (x *PrimitiveType) GetValue() *PrimitiveType_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type StringIntegerValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Value:
	//
	//	*StringIntegerValue_Text
	//	*StringIntegerValue_Number
	Value isStringIntegerValue_Value `protobuf_oneof:"value"`
}

func (x *StringIntegerValue) Reset() {
	*x = StringIntegerValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_def_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringIntegerValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringIntegerValue) ProtoMessage() {}

func (x *StringIntegerValue) ProtoReflect() protoreflect.Message {
	mi := &file_types_def_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringIntegerValue.ProtoReflect.Descriptor instead.
func (*StringIntegerValue) Descriptor() ([]byte, []int) {
	return file_types_def_proto_rawDescGZIP(), []int{14}
}

func (m *StringIntegerValue) GetValue() isStringIntegerValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *StringIntegerValue) GetText() string {
	if x, ok := x.GetValue().(*StringIntegerValue_Text); ok {
		return x.Text
	}
	return ""
}

func (x *StringIntegerValue) GetNumber() int64 {
	if x, ok := x.GetValue().(*StringIntegerValue_Number); ok {
		return x.Number
	}
	return 0
}

type isStringIntegerValue_Value interface {
	isStringIntegerValue_Value()
}

type StringIntegerValue_Text struct {
	Text string `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type StringIntegerValue_Number struct {
	Number int64 `protobuf:"varint,2,opt,name=number,proto3,oneof"`
}

func (*StringIntegerValue_Text) isStringIntegerValue_Value() {}

func (*StringIntegerValue_Number) isStringIntegerValue_Value() {}

type PrimitiveType_Value struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Element:
	//
	//	*PrimitiveType_Value_Text
	//	*PrimitiveType_Value_DoubleValue
	//	*PrimitiveType_Value_Int64Value
	//	*PrimitiveType_Value_Uint64Value
	//	*PrimitiveType_Value_Boolean
	//	*PrimitiveType_Value_RawBytes
	Element isPrimitiveType_Value_Element `protobuf_oneof:"element"`
}

func (x *PrimitiveType_Value) Reset() {
	*x = PrimitiveType_Value{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_def_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrimitiveType_Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrimitiveType_Value) ProtoMessage() {}

func (x *PrimitiveType_Value) ProtoReflect() protoreflect.Message {
	mi := &file_types_def_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrimitiveType_Value.ProtoReflect.Descriptor instead.
func (*PrimitiveType_Value) Descriptor() ([]byte, []int) {
	return file_types_def_proto_rawDescGZIP(), []int{13, 0}
}

func (m *PrimitiveType_Value) GetElement() isPrimitiveType_Value_Element {
	if m != nil {
		return m.Element
	}
	return nil
}

func (x *PrimitiveType_Value) GetText() string {
	if x, ok := x.GetElement().(*PrimitiveType_Value_Text); ok {
		return x.Text
	}
	return ""
}

func (x *PrimitiveType_Value) GetDoubleValue() float64 {
	if x, ok := x.GetElement().(*PrimitiveType_Value_DoubleValue); ok {
		return x.DoubleValue
	}
	return 0
}

func (x *PrimitiveType_Value) GetInt64Value() int64 {
	if x, ok := x.GetElement().(*PrimitiveType_Value_Int64Value); ok {
		return x.Int64Value
	}
	return 0
}

func (x *PrimitiveType_Value) GetUint64Value() uint64 {
	if x, ok := x.GetElement().(*PrimitiveType_Value_Uint64Value); ok {
		return x.Uint64Value
	}
	return 0
}

func (x *PrimitiveType_Value) GetBoolean() bool {
	if x, ok := x.GetElement().(*PrimitiveType_Value_Boolean); ok {
		return x.Boolean
	}
	return false
}

func (x *PrimitiveType_Value) GetRawBytes() []byte {
	if x, ok := x.GetElement().(*PrimitiveType_Value_RawBytes); ok {
		return x.RawBytes
	}
	return nil
}

type isPrimitiveType_Value_Element interface {
	isPrimitiveType_Value_Element()
}

type PrimitiveType_Value_Text struct {
	Text string `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type PrimitiveType_Value_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,2,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type PrimitiveType_Value_Int64Value struct {
	Int64Value int64 `protobuf:"varint,3,opt,name=int64_value,json=int64Value,proto3,oneof"`
}

type PrimitiveType_Value_Uint64Value struct {
	Uint64Value uint64 `protobuf:"varint,4,opt,name=uint64_value,json=uint64Value,proto3,oneof"`
}

type PrimitiveType_Value_Boolean struct {
	Boolean bool `protobuf:"varint,5,opt,name=boolean,proto3,oneof"`
}

type PrimitiveType_Value_RawBytes struct {
	RawBytes []byte `protobuf:"bytes,6,opt,name=raw_bytes,json=rawBytes,proto3,oneof"`
}

func (*PrimitiveType_Value_Text) isPrimitiveType_Value_Element() {}

func (*PrimitiveType_Value_DoubleValue) isPrimitiveType_Value_Element() {}

func (*PrimitiveType_Value_Int64Value) isPrimitiveType_Value_Element() {}

func (*PrimitiveType_Value_Uint64Value) isPrimitiveType_Value_Element() {}

func (*PrimitiveType_Value_Boolean) isPrimitiveType_Value_Element() {}

func (*PrimitiveType_Value_RawBytes) isPrimitiveType_Value_Element() {}

var File_types_def_proto protoreflect.FileDescriptor

var file_types_def_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x5f, 0x64, 0x65, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x30, 0x0a, 0x18, 0x57, 0x69, 0x74, 0x68, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x22, 0x66, 0x0a, 0x10, 0x57, 0x69, 0x74, 0x68, 0x4f, 0x6e, 0x65, 0x6f, 0x66,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x12, 0x14, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x42, 0x0e, 0x0a, 0x0c, 0x6f,
	0x6e, 0x65, 0x5f, 0x6f, 0x66, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x53, 0x0a, 0x11, 0x57,
	0x69, 0x74, 0x68, 0x4f, 0x6e, 0x65, 0x6f, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x48, 0x00, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x04, 0x74, 0x65,
	0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74,
	0x42, 0x0e, 0x0a, 0x0c, 0x6f, 0x6e, 0x65, 0x5f, 0x6f, 0x66, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x58, 0x0a, 0x14, 0x57, 0x69, 0x74, 0x68, 0x50, 0x72, 0x69, 0x6d, 0x69, 0x74, 0x69, 0x76,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x09, 0x70, 0x72, 0x69, 0x6d,
	0x69, 0x74, 0x69, 0x76, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x50, 0x72,
	0x69, 0x6d, 0x69, 0x74, 0x69, 0x76, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x70, 0x72, 0x69,
	0x6d, 0x69, 0x74, 0x69, 0x76, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x45, 0x0a, 0x15, 0x57, 0x69,
	0x74, 0x68, 0x50, 0x72, 0x69, 0x6d, 0x69, 0x74, 0x69, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x09, 0x70, 0x72, 0x69, 0x6d, 0x69, 0x74, 0x69, 0x76, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x50, 0x72, 0x69, 0x6d, 0x69, 0x74, 0x69,
	0x76, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x70, 0x72, 0x69, 0x6d, 0x69, 0x74, 0x69, 0x76,
	0x65, 0x22, 0x62, 0x0a, 0x13, 0x57, 0x69, 0x74, 0x68, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x0c, 0x6f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00,
	0x52, 0x0b, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x88, 0x01, 0x01,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x4f, 0x0a, 0x14, 0x57, 0x69, 0x74, 0x68, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a,
	0x0c, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x0b, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x4b, 0x0a, 0x18, 0x57, 0x69, 0x74, 0x68, 0x52, 0x65,
	0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6e, 0x74, 0x5f, 0x61, 0x72, 0x72, 0x61, 0x79, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x22, 0x38, 0x0a, 0x19, 0x57, 0x69, 0x74, 0x68, 0x52, 0x65, 0x70, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6e, 0x74, 0x5f, 0x61, 0x72, 0x72, 0x61, 0x79, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x03, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x41, 0x72, 0x72, 0x61, 0x79, 0x22, 0x71, 0x0a,
	0x1c, 0x57, 0x69, 0x74, 0x68, 0x52, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x49, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3d, 0x0a,
	0x10, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x69, 0x6e, 0x74, 0x5f, 0x61, 0x72, 0x72, 0x61,
	0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x49, 0x6e, 0x74, 0x65, 0x67, 0x65, 0x72, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x0e, 0x73, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x74, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x22, 0x5e, 0x0a, 0x1d, 0x57, 0x69, 0x74, 0x68, 0x52, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x3d, 0x0a, 0x10, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x69, 0x6e, 0x74, 0x5f,
	0x61, 0x72, 0x72, 0x61, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x53, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x65, 0x72, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x52, 0x0e, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x74, 0x41, 0x72, 0x72, 0x61, 0x79,
	0x22, 0x9d, 0x01, 0x0a, 0x0e, 0x57, 0x69, 0x74, 0x68, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x3a, 0x0a, 0x09, 0x6d, 0x61, 0x70, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x57, 0x69, 0x74, 0x68, 0x4d, 0x61, 0x70,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4d, 0x61, 0x70, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x6d, 0x61, 0x70, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x1a, 0x3b, 0x0a, 0x0d, 0x4d, 0x61, 0x70, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x22, 0x8b, 0x01, 0x0a, 0x0f, 0x57, 0x69, 0x74, 0x68, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x09, 0x6d, 0x61, 0x70, 0x5f, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x57, 0x69, 0x74, 0x68, 0x4d, 0x61,
	0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4d, 0x61, 0x70, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x6d, 0x61, 0x70, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x1a, 0x3b, 0x0a, 0x0d, 0x4d, 0x61, 0x70, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x8e,
	0x02, 0x0a, 0x0d, 0x50, 0x72, 0x69, 0x6d, 0x69, 0x74, 0x69, 0x76, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x2a, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x50, 0x72, 0x69, 0x6d, 0x69, 0x74, 0x69, 0x76, 0x65, 0x54, 0x79, 0x70, 0x65, 0x2e,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0xd0, 0x01, 0x0a,
	0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x23, 0x0a, 0x0c,
	0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x01, 0x48, 0x00, 0x52, 0x0b, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x21, 0x0a, 0x0b, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x0a, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x23, 0x0a, 0x0c, 0x75, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x5f, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00, 0x52, 0x0b, 0x75, 0x69,
	0x6e, 0x74, 0x36, 0x34, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1a, 0x0a, 0x07, 0x62, 0x6f, 0x6f,
	0x6c, 0x65, 0x61, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x07, 0x62, 0x6f,
	0x6f, 0x6c, 0x65, 0x61, 0x6e, 0x12, 0x1d, 0x0a, 0x09, 0x72, 0x61, 0x77, 0x5f, 0x62, 0x79, 0x74,
	0x65, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x08, 0x72, 0x61, 0x77, 0x42,
	0x79, 0x74, 0x65, 0x73, 0x42, 0x09, 0x0a, 0x07, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x22,
	0x4d, 0x0a, 0x12, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x65, 0x72,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x18, 0x0a, 0x06, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x06, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0xde,
	0x03, 0x0a, 0x08, 0x54, 0x79, 0x70, 0x65, 0x73, 0x44, 0x65, 0x66, 0x12, 0x43, 0x0a, 0x09, 0x57,
	0x69, 0x74, 0x68, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x12, 0x19, 0x2e, 0x57, 0x69, 0x74, 0x68, 0x49,
	0x6e, 0x74, 0x36, 0x34, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x1a, 0x19, 0x2e, 0x57, 0x69, 0x74, 0x68, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x34, 0x0a, 0x09, 0x57, 0x69, 0x74, 0x68, 0x4f, 0x6e, 0x65, 0x6f, 0x66, 0x12, 0x11, 0x2e,
	0x57, 0x69, 0x74, 0x68, 0x4f, 0x6e, 0x65, 0x6f, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x12, 0x2e, 0x57, 0x69, 0x74, 0x68, 0x4f, 0x6e, 0x65, 0x6f, 0x66, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x0d, 0x57, 0x69, 0x74, 0x68, 0x50, 0x72,
	0x69, 0x6d, 0x69, 0x74, 0x69, 0x76, 0x65, 0x12, 0x15, 0x2e, 0x57, 0x69, 0x74, 0x68, 0x50, 0x72,
	0x69, 0x6d, 0x69, 0x74, 0x69, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16,
	0x2e, 0x57, 0x69, 0x74, 0x68, 0x50, 0x72, 0x69, 0x6d, 0x69, 0x74, 0x69, 0x76, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x0c, 0x57, 0x69, 0x74, 0x68,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x12, 0x14, 0x2e, 0x57, 0x69, 0x74, 0x68, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15,
	0x2e, 0x57, 0x69, 0x74, 0x68, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4c, 0x0a, 0x11, 0x57, 0x69, 0x74, 0x68, 0x52,
	0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x12, 0x19, 0x2e, 0x57,
	0x69, 0x74, 0x68, 0x52, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x49, 0x6e, 0x74, 0x36, 0x34,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x57, 0x69, 0x74, 0x68, 0x52, 0x65,
	0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x58, 0x0a, 0x15, 0x57, 0x69, 0x74, 0x68, 0x52, 0x65, 0x70,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x74, 0x12, 0x1d,
	0x2e, 0x57, 0x69, 0x74, 0x68, 0x52, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x49, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e,
	0x57, 0x69, 0x74, 0x68, 0x52, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x53, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x49, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x2e, 0x0a, 0x07, 0x57, 0x69, 0x74, 0x68, 0x4d, 0x61, 0x70, 0x12, 0x0f, 0x2e, 0x57, 0x69, 0x74,
	0x68, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x57, 0x69,
	0x74, 0x68, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x1b, 0x5a, 0x19, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2d, 0x74, 0x65, 0x73, 0x74, 0x2f,
	0x67, 0x72, 0x70, 0x63, 0x2f, 0x61, 0x70, 0x69, 0x74, 0x65, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_types_def_proto_rawDescOnce sync.Once
	file_types_def_proto_rawDescData = file_types_def_proto_rawDesc
)

func file_types_def_proto_rawDescGZIP() []byte {
	file_types_def_proto_rawDescOnce.Do(func() {
		file_types_def_proto_rawDescData = protoimpl.X.CompressGZIP(file_types_def_proto_rawDescData)
	})
	return file_types_def_proto_rawDescData
}

var file_types_def_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_types_def_proto_goTypes = []interface{}{
	(*WithInt64RequestResponse)(nil),      // 0: WithInt64RequestResponse
	(*WithOneofRequest)(nil),              // 1: WithOneofRequest
	(*WithOneofResponse)(nil),             // 2: WithOneofResponse
	(*WithPrimitiveRequest)(nil),          // 3: WithPrimitiveRequest
	(*WithPrimitiveResponse)(nil),         // 4: WithPrimitiveResponse
	(*WithOptionalRequest)(nil),           // 5: WithOptionalRequest
	(*WithOptionalResponse)(nil),          // 6: WithOptionalResponse
	(*WithRepeatedInt64Request)(nil),      // 7: WithRepeatedInt64Request
	(*WithRepeatedInt64Response)(nil),     // 8: WithRepeatedInt64Response
	(*WithRepeatedStringIntRequest)(nil),  // 9: WithRepeatedStringIntRequest
	(*WithRepeatedStringIntResponse)(nil), // 10: WithRepeatedStringIntResponse
	(*WithMapRequest)(nil),                // 11: WithMapRequest
	(*WithMapResponse)(nil),               // 12: WithMapResponse
	(*PrimitiveType)(nil),                 // 13: PrimitiveType
	(*StringIntegerValue)(nil),            // 14: StringIntegerValue
	nil,                                   // 15: WithMapRequest.MapValueEntry
	nil,                                   // 16: WithMapResponse.MapValueEntry
	(*PrimitiveType_Value)(nil),           // 17: PrimitiveType.Value
}
var file_types_def_proto_depIdxs = []int32{
	13, // 0: WithPrimitiveRequest.primitive:type_name -> PrimitiveType
	13, // 1: WithPrimitiveResponse.primitive:type_name -> PrimitiveType
	14, // 2: WithRepeatedStringIntRequest.string_int_array:type_name -> StringIntegerValue
	14, // 3: WithRepeatedStringIntResponse.string_int_array:type_name -> StringIntegerValue
	15, // 4: WithMapRequest.map_value:type_name -> WithMapRequest.MapValueEntry
	16, // 5: WithMapResponse.map_value:type_name -> WithMapResponse.MapValueEntry
	17, // 6: PrimitiveType.value:type_name -> PrimitiveType.Value
	0,  // 7: TypesDef.WithInt64:input_type -> WithInt64RequestResponse
	1,  // 8: TypesDef.WithOneof:input_type -> WithOneofRequest
	3,  // 9: TypesDef.WithPrimitive:input_type -> WithPrimitiveRequest
	5,  // 10: TypesDef.WithOptional:input_type -> WithOptionalRequest
	7,  // 11: TypesDef.WithRepeatedInt64:input_type -> WithRepeatedInt64Request
	9,  // 12: TypesDef.WithRepeatedStringInt:input_type -> WithRepeatedStringIntRequest
	11, // 13: TypesDef.WithMap:input_type -> WithMapRequest
	0,  // 14: TypesDef.WithInt64:output_type -> WithInt64RequestResponse
	2,  // 15: TypesDef.WithOneof:output_type -> WithOneofResponse
	4,  // 16: TypesDef.WithPrimitive:output_type -> WithPrimitiveResponse
	6,  // 17: TypesDef.WithOptional:output_type -> WithOptionalResponse
	8,  // 18: TypesDef.WithRepeatedInt64:output_type -> WithRepeatedInt64Response
	10, // 19: TypesDef.WithRepeatedStringInt:output_type -> WithRepeatedStringIntResponse
	12, // 20: TypesDef.WithMap:output_type -> WithMapResponse
	14, // [14:21] is the sub-list for method output_type
	7,  // [7:14] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_types_def_proto_init() }
func file_types_def_proto_init() {
	if File_types_def_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_types_def_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithInt64RequestResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_def_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithOneofRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_def_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithOneofResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_def_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithPrimitiveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_def_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithPrimitiveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_def_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithOptionalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_def_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithOptionalResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_def_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithRepeatedInt64Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_def_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithRepeatedInt64Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_def_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithRepeatedStringIntRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_def_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithRepeatedStringIntResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_def_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithMapRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_def_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithMapResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_def_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrimitiveType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_def_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StringIntegerValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_def_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrimitiveType_Value); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_types_def_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*WithOneofRequest_Number)(nil),
		(*WithOneofRequest_Text)(nil),
	}
	file_types_def_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*WithOneofResponse_Number)(nil),
		(*WithOneofResponse_Text)(nil),
	}
	file_types_def_proto_msgTypes[5].OneofWrappers = []interface{}{}
	file_types_def_proto_msgTypes[6].OneofWrappers = []interface{}{}
	file_types_def_proto_msgTypes[14].OneofWrappers = []interface{}{
		(*StringIntegerValue_Text)(nil),
		(*StringIntegerValue_Number)(nil),
	}
	file_types_def_proto_msgTypes[17].OneofWrappers = []interface{}{
		(*PrimitiveType_Value_Text)(nil),
		(*PrimitiveType_Value_DoubleValue)(nil),
		(*PrimitiveType_Value_Int64Value)(nil),
		(*PrimitiveType_Value_Uint64Value)(nil),
		(*PrimitiveType_Value_Boolean)(nil),
		(*PrimitiveType_Value_RawBytes)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_types_def_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_types_def_proto_goTypes,
		DependencyIndexes: file_types_def_proto_depIdxs,
		MessageInfos:      file_types_def_proto_msgTypes,
	}.Build()
	File_types_def_proto = out.File
	file_types_def_proto_rawDesc = nil
	file_types_def_proto_goTypes = nil
	file_types_def_proto_depIdxs = nil
}
