// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.22.3
// source: types_def.proto

package apitest

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TypesDefClient is the client API for TypesDef service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TypesDefClient interface {
	VariousDef(ctx context.Context, in *VariousDefRequest, opts ...grpc.CallOption) (*VariousDefResponse, error)
}

type typesDefClient struct {
	cc grpc.ClientConnInterface
}

func NewTypesDefClient(cc grpc.ClientConnInterface) TypesDefClient {
	return &typesDefClient{cc}
}

func (c *typesDefClient) VariousDef(ctx context.Context, in *VariousDefRequest, opts ...grpc.CallOption) (*VariousDefResponse, error) {
	out := new(VariousDefResponse)
	err := c.cc.Invoke(ctx, "/TypesDef/VariousDef", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TypesDefServer is the server API for TypesDef service.
// All implementations must embed UnimplementedTypesDefServer
// for forward compatibility
type TypesDefServer interface {
	VariousDef(context.Context, *VariousDefRequest) (*VariousDefResponse, error)
	mustEmbedUnimplementedTypesDefServer()
}

// UnimplementedTypesDefServer must be embedded to have forward compatible implementations.
type UnimplementedTypesDefServer struct {
}

func (UnimplementedTypesDefServer) VariousDef(context.Context, *VariousDefRequest) (*VariousDefResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VariousDef not implemented")
}
func (UnimplementedTypesDefServer) mustEmbedUnimplementedTypesDefServer() {}

// UnsafeTypesDefServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TypesDefServer will
// result in compilation errors.
type UnsafeTypesDefServer interface {
	mustEmbedUnimplementedTypesDefServer()
}

func RegisterTypesDefServer(s grpc.ServiceRegistrar, srv TypesDefServer) {
	s.RegisterService(&TypesDef_ServiceDesc, srv)
}

func _TypesDef_VariousDef_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VariousDefRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TypesDefServer).VariousDef(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TypesDef/VariousDef",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TypesDefServer).VariousDef(ctx, req.(*VariousDefRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TypesDef_ServiceDesc is the grpc.ServiceDesc for TypesDef service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TypesDef_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "TypesDef",
	HandlerType: (*TypesDefServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VariousDef",
			Handler:    _TypesDef_VariousDef_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "types_def.proto",
}
